### ISSUE TITLE
Working with processes with multiple enquiry periods

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#10]
How do we handle the case when there is more than one enquiry period for a project.

**Comment by timgdavies** [comment]
In the MX experience - there are:

(a) Changes to the enquiry period;

(b) Second rounds of enquiries and consultation;

**Comment by timgdavies** [comment]
We're looking at handling this by:

* Using the existing OCDS field for ```enquiryPeriod ``` to reflect the **next**, **current**, **most recent** period of enquiry.

* Capture any details of future planned periods of enquiry as milestones in ```tender```.

Where red flag or other analysis needs to rely upon looking at the number, and duration, of periods of enquiry, this will need either use of the versioned release or looking through past releases to compare periods.

This proposal is based on looking at existing data from procurement systems, which rarely appear to model multiple periods of enquiry, so would be updating the data in their systems in any case.

**Comment by duncandewhurst** [comment]
Enquiry period start and end codes added to milestone code codelist (see #37)
