### ISSUE TITLE
Reporting issues on OCDS extensions

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#105]
Remove this line in `governance.md`:

    Issues related to the individual extensions that make up the implementation profile can be raised on their respective GitHub projects.

How to report issues is described in each extension's readme, but GitHub Issues is not necessarily enabled on each GitHub repository.

**Comment by duncandewhurst** [comment]
Noting that:

* the updates to the extension readmes haven't yet been merged.
* we will need to create new pinned versions of the extension repos to pull those changes in once they are merged
* changing this text would require updates to translations

I propose we leave this for now - on the basis that users who go to the individual extension repository to report an issue will see the updated readmes (once they are merged).

I'll leave the issue open to remind us to update this once the readmes are updated and once the current translations have been deployed.

**Comment by jpmckinney** [comment]
Sounds good re: this issue. For the PRs, I can merge them all - I'm just waiting for a go-ahead: https://github.com/open-contracting/standard-development-handbook/issues/23#issuecomment-325745879

**Comment by jpmckinney** [comment]
> users who go to the individual extension repository to report an issue will see the updated readmes

This is sufficient, so closing.
