### ISSUE TITLE
Broken links in schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#129]
Links within the field descriptions in the PPP schema that point to the OCDS documentation are broken (they contain placeholders for {{version}} and {{lang}}).

This occurs in both the [JSON schema](http://standard.open-contracting.org/profiles/ppp/master/en/_static/ppp-release-schema.json) and the [schema reference in the docs](http://standard.open-contracting.org/profiles/ppp/master/en/reference/schema/)

**Comment by jpmckinney** [comment]
Those placeholders get replaced in the `confpy` branch (which should be merged). The links won't work on that branch until it's merged, as the links will try the non-existent `confpy` build of the standard docs; once merged, they will try the existing `latest`build.

Broken build: http://standard.open-contracting.org/profiles/ppp/latest/en/reference/schema/

Confpy build: http://standard.open-contracting.org/profiles/ppp/confpy/en/reference/schema/

**Comment by jpmckinney** [comment]
Working now that confpy is merged.
