### ISSUE TITLE
Indicators and performance reporting

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#13]
At the planning stage a PPP may set out **targets** to be met.

At the bid state, bidders may indicate how far they feel they can meet those targets.

At the award and contract stage, agreed targets may be established.

At the implementation stage, progress towards those targets may be reported.

**Comment by timgdavies** [comment]
There are some relationships between what we need for PPP targets, and the proposed [features extension](https://github.com/open-contracting/standard/issues/223) in use in Ukraine. 

We could consider an adaptation of the ```features``` array in terms of a ```metrics``` array.

**Comment by dc-coder** [comment]
Just some additional thoughts on this: 
The PPP framework also says that there are lists of reports, documents and other information that the private provider should maintain and submit at regular times. There will be penalties for non submissions. 

So when it comes to publishing performance reports, I guess there might be extra disclosure forms/IT system/fields that need to be designed. Those might be very different from project/country to another.
