### ISSUE TITLE
Updating translations

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#130]
To sort translations, I'll:

* [x] push to Transifex
* [x] resolve the 90%+ matches for typo fixes
* [x] [copy translations from the standard](http://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/#copying-translations-from-the-standard-to-a-profile), where possible, for the updated extensions
* [x] ask ILDA to translate remaining strings (should be few, and limited to community extensions)
* [x] pull from Transifex

The recently merged `confpy` branch used the `master` branch of the extension registry. I need to check what impact this has on the built documentation (besides getting the latest version of extensions, which is desirable); the impact may be limited to the GitHub URLs of extensions. Since we are moving towards [eliminating branches from the extension registry](https://github.com/open-contracting/extension_registry/issues/85), we may pursue a stop-gap method here, rather than updating the `ppp` branch of the extension registry.

cc @duncandewhurst in case anything to add or correct above.

**Comment by duncandewhurst** [comment]
Sounds good.

We did spot a few untranslated strings outside of community extensions, e.g. on the homepage of the docs and on the spreadsheet template page, but they should be picked up by ILDA translating the remaining strings

Some of the changes in https://github.com/open-contracting/public-private-partnerships/pull/125 look like they will require translation, so we should try to get that merged before ILDA update the translation

**Comment by jpmckinney** [comment]
#125 is merged. I also fixed #127 in #131.

We can wait on #126 for translations.

**Comment by duncandewhurst** [comment]
@jpmckinney I think we should be OK for ILDA to start work on translations now?

**Comment by jpmckinney** [comment]
@duncandewhurst In terms of priority/urgency, is there a strong demand to do that very soon? If not, I might prefer to sort out #156 and #159.

**Comment by duncandewhurst** [comment]
Since two of the work in progress implementations are Spanish language, I think we should prioritise updating the translations, as currently the Spanish version of the docs will have chunks in English.

It can be done in parallel to #156 and #159 since neither of those should impact on the strings which need to be translated or have a noticeable impact on users (noting that CoVE isn't yet wired up to display translated error messages per https://github.com/open-contracting/standard/issues/704)

**Comment by jpmckinney** [comment]
Okay, feel free to run the steps here: http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/translation/technical/#push-translations-to-transifex

**Comment by duncandewhurst** [comment]
@jpmckinney great, I've run the steps
