### ISSUE TITLE
Schema issues

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#135]
Now that we've corrected most issues in extensions, we can more easily see what's at issue in the profile itself:

* [x] release-schema.json has unused codelists: metricID.csv, milestoneCode.csv. I don't what what those two codelists are for, but they indeed are not used.

`release-schema.json` introduces a `Project` definition which is not referenced anywhere. Can we delete it? (It causes tests to fail.) If we keep it:

* [x] release-schema.json is missing /definitions/Project/title
* [x] release-schema.json is missing /definitions/Project/description

----

I noticed some more issues in extensions. Reporting here:

* [x] ocds_budget_projects_extension: release-schema.json has optional but non-nullable object at /definitions/Planning/properties/project
* [x] ocds_partyDetails_scale_extension has an empty code ",Not specified,No party scale is specified". If it's not specified, the field should simply not be set. In OCDS, we don't distinguish between "unknown value" and "no value". The inclusion of a blank code causes a codelist test to fail.

**Comment by duncandewhurst** [comment]
I've added both metricID.csv and milestoneCode.csv to release-schema.json in https://github.com/open-contracting/public-private-partnerships/pull/138, see below for an explanation of how these codelists are used:

**metricID**

The description of `metrics/id` in the metrics extension states that:

> In some cases this may be drawn from a codelist of metrics required for this type of contracting process, or in other instances may be an arbitrary identifier.

The PPP profile introduces the metricID codelist for common types of metric for PPPs, e.g. reporting [the actual annual demand in the implementation phase](http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#x-1-actual-annual-demand), where:

> A metric with the id ‘demand’ should be given, with a series of actual observations that capture the actual demand for a given period.

**milestoneCode**

In the core schema the description of `milestones/code` states that:

> Milestone codes can be used to track specific events that take place for a particular kind of contracting process. For example, a code of 'approvalLetter' could be used to allow applications to understand this milestone represents the date an approvalLetter is due or signed. Milestone codes is an open codelist, and codes should be agreed among data producers and the applications using that data.

The core schema doesn't define any codes for `milestoneCode` but the PPP profile introduces codes for common types of PPP milestone, e.g. the [date of financial close](http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#i-11-2-contract-milestones-date-of-financial-close):

> The milestone should have a type of ‘financing’, a code of ‘financialClose’

**Comment by duncandewhurst** [comment]
The orphaned `Project` definition was caused by [refactoring the budgets and projects extension](https://github.com/open-contracting/ocds_budget_projects_extension/commit/572a936918e86a3b3123f7468f9e53e98e7e32d7#diff-b07d550471924be8c07891e3e566661f) to remove redundant titles and descriptions, which involved removing the $ref to the `Project` definition which the PPP profile extends.

Since we don't reuse the `Project` definition anywhere else, I've refactored the PPP profile too in https://github.com/open-contracting/public-private-partnerships/pull/139, but noting that this does lead to nested properties

**Comment by jpmckinney** [comment]
Closed via related PRs above.
