### ISSUE TITLE
Move PPP profile to new repository, move consolidated extension to root directory

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#156]
As discussed as a follow-up to #142.

@duncandewhurst Would you be able to take this forward in coming weeks? It's not a first priority, but as you've been in the headspace, I figure it's a good opportunity to do this follow-up.

See [this comment](https://github.com/open-contracting/public-private-partnerships/issues/142#issuecomment-398219044) for proposed steps. I will also likely want to update the tests in standard-maintenance-scripts to remove some special cases for profiles.

**Comment by duncandewhurst** [comment]
Sure, no problem

**Comment by jpmckinney** [comment]
@duncandewhurst Let me know when you think you will have time for this issue. (I don't mind doing it as part of the mentioned work on `apply_extensions`, but if you were planning on doing it shortly, that'd be great.)

**Comment by duncandewhurst** [comment]
I will try and get to this next week

**Comment by jpmckinney** [comment]
I coordinated with @duncandewhurst via email that I would start on this.
