### ISSUE TITLE
Versioning the PPP profile

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#157]
Currently the PPP profile doesn't have a formal version number or status and whilst the profile hasn't yet been formally launched, there are several publishers working on publishing OCDS for PPPs data, so we should aim to provide them with a stable version to implement against.

If we give the current version of the profile a name or number, then we can follow a similar approach to the core standard and create an archive branch for it in the Github repository (e.g. https://github.com/open-contracting/standard/tree/1.0) and maintain a historic copy of the built docs (e.g. http://standard.open-contracting.org/legacy/r/1__0__0/en/), to refer to once future updates have been made.

Since the initial implementations are work in progress and we haven't yet received much feedback it seems premature to declare this version 1.0 so I propose we name the current version 'beta'.

The [governance section](http://standard.open-contracting.org/profiles/ppp/latest/en/governance/) of the profile docs states that:

> As an implementation profile, extending OCDS 1.1, updates to the core schema will be subject to the OCDS Governance Process.

I'm not sure whether this implies that the PPP profile should be versioned in sync with the core standard, or how a beta release would fit into the OCDS governance process, noting in particular that many of the extensions which constitute the PPP profile are community extensions which are not subject to the governance process.

@timgdavies @jpmckinney @LindseyAM your thoughts?

**Comment by jpmckinney** [comment]
I propose we start a `1.0` branch and call the release `1.0.0-beta`.

"Core schema", in my mind, only refers to the schema files of OCDS, so when I read the sentence, it is simply restating that changes to OCDS are subject to its governance process.

Anyhow, I don't think that profiles *must* be versioned in sync with the core standard – though if a minor version of OCDS deprecates any fields, I imagine we'd want to release new versions of any profiles or extensions that use those fields.

Profiles are not covered under our [normative and non-normative policy](https://docs.google.com/document/d/1xjlAneqgewZvHh6_hwuQ98hbjxRcA2IUqOTJiNGcOf8/edit). I don't think that they must in all cases be subject to the governance process. To my knowledge, OCDS for PPPs hasn't followed that process, so I'd be in favour of keeping it that way. Introducing the governance process, at this point, whose review could cause significant changes, which we may want to avoid given that many publishers are working on it already.

**Comment by timgdavies** [comment]
I'm happy with the proposal here.

**Comment by jpmckinney** [comment]
Lindsey as well. I created the `1.0` branch.

I'll rename `master` to `1.0-dev`.

When we're ready for a release (perhaps after closing some remaining issues), we can use `1.0.0-beta`.

(The extensions use dots in tag names, but the standard uses double underscores like `1__0__0-beta`. I would prefer to have the OCDS for PPPs tag names match the way we refer to versions in prose, unless there was a strong reason to use double underscores. It's possible double underscores were used to avoid collisions with branch names, but, perhaps since then, practice has evolved to have minor version branches only, so patch version tags shouldn't collide with branch names.)

**Comment by jpmckinney** [comment]
I've updated the handbook to match this proposal: https://github.com/open-contracting/standard-development-handbook/pull/186
