### ISSUE TITLE
Create a live branch

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#158]
In relation to #157 I noticed that we aren't currently following the practice from the [standard development handbook](http://ocds-standard-development-handbook.readthedocs.io/en/latest/profiles/#branches):

> The development version of a profile is on the `master` branch, and the live version is on the `live` branch.

So, in the meantime should we simply create a `live` branch so that the commit that the current live version was deployed from is easy to locate?

@timgdavies @jpmckinney

**Comment by jpmckinney** [comment]
Since the documentation at `latest` needs to be copied into place, I think things may be fine as-is for the short term. Once we settle on a versioning scheme in #157, version names will take the place of `live`. If that's fine, we can update the handbook accordingly.

**Comment by jpmckinney** [comment]
Noting that that line in the handbook was introduced in this commit: https://github.com/open-contracting/standard-development-handbook/commit/101614d5d0636440fc6e6138b79ec9b7e811f944

**Comment by jpmckinney** [comment]
Based on discussion in #157, we'll have `latest`, `1.0` and `1.0-dev` branches, as we do for the standard. http://ocds-standard-development-handbook.readthedocs.io/en/latest/standard/technical/repository/#branches-and-tags
