### ISSUE TITLE
Translating the consolidated extension

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#159]
Currently the patched PPP schema and compiled codelists for the PPP profile are translated as part of the docs build.

Prior to the changes in #142 publishers declared the PPP profile by declaring the individual extensions which comprise it and because extensions aren't translated at source these were the EN versions of the extensions.

Following the changes in #142 publishers now declare the PPP profile by declaring the consolidated extension and because the consolidated extension is built from the untranslated extensions (using `apply-extensions.py`) this is also untranslated.

For anyone developing a tool to publish OCDS for PPPs data, they can use the full schema (which is translated), for example to display field descriptions in an interface, but for 'extension aware' tooling which consumes OCDS data, e.g. to display translated field descriptions in CoVE, we would need to have a translated version of the consolidated extension for users to declare.

This is related to https://github.com/open-contracting/standard/issues/704.

**Comment by jpmckinney** [comment]
Note that the strings for this are captured by #164, so once merged we can extract and push strings to Transifex. Then, we can add a filename to the `translate_schema` call, so that the translation becomes available.

**Comment by jpmckinney** [comment]
@duncandewhurst Would we want the consolidated extension to be available in different languages at each of the following?

* http://standard.open-contracting.org/profiles/ppp/latest/en/
* http://standard.open-contracting.org/profiles/ppp/latest/es/

**Comment by jpmckinney** [comment]
In our [translation policy](https://docs.google.com/document/d/1GLwWTpgDDkKmMr1hZE4D75LI8VQtFiD0VA7TF_FvY_Q/edit#):

> The authoritative language for the standard is English. All translations into other languages are provided for the convenience of users, and in case of conflict or ambiguity, the English text supersedes all translations.

I'm thinking we probably only want a given version of an extension or profile to have a single base URL. This is in line with the translations being conveniences as described above.

The standard follows those principles. The canonical base URL for the schema of OCDS 1.1.3 is http://standard.open-contracting.org/schema/1__1__3/, but we offer translations at the base URLs:

* http://standard.open-contracting.org/latest/en/
* http://standard.open-contracting.org/latest/es/
* http://standard.open-contracting.org/latest/fr/

Presently, the canonical base URL for this profile includes the `en` language code, which is perhaps okay, though a base URL without any language codes may have been preferred.

Anyhow, I think we want to encourage the declaration of extensions and profiles using a canonical English base URL, similar to how we encourage the declaration of OCDS schema using the canonical URL above. Thoughts on how to do that?

**Comment by jpmckinney** [comment]
If we sort out #157, then we can use as a canonical URL similar to the standards, instead of a canonical URL with `latest` and `en` in it, e.g.

http://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta/

**Comment by duncandewhurst** [comment]
Agreed, it would be good to mirror the approach used in the main standard here and have a canonical url without the language.

I think there's an unresolved question as to how extensions in general are declared for data in languages other than English, i.e. how do we make sure extension aware tooling such as CoVE is able to access translated versions of the field titles and descriptions used in an extension.

@timgdavies suggested in https://github.com/open-contracting/standard/issues/704 that:

> We support content negotiation for language so that, when the validator is requesting schema files, it can request translated copies.

**Comment by jpmckinney** [comment]
I think the work being done on https://github.com/open-contracting/extensions-data-collector is likely to provide a way to retrieve translated schema and codelists.

^ Also, I think you meant just without the language (`en`), not without the version (`1__0__0__beta`)?

**Comment by duncandewhurst** [comment]
> Also, I think you meant just without the language (en), not without the version (1__0__0__beta)?

I did indeed mean that (and I've edited the original comment).

Should we leave this issue open until the other work on extensions has provided a way to retrieve a translated version of the consolidated extension?

**Comment by jpmckinney** [comment]
With #171, it will be possible to get translated versions of the consolidated extension at the convenience URL of e.g. http://standard.open-contracting.org/profiles/ppp/translated-consolidated-extension/es/release-schema.json

We can explore alternative methods like content negotiation, etc. through the extension explorer / extensions-data-collector. The present method of substituting the language part within a known URL pattern seems sufficient for this issue. So, I think we can close this issue once #171 is closed.
