### ISSUE TITLE
Using version and language placeholders in the documentation and sample data

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#160]
Following the changes in #142 publishers now declare the profile using the consolidated extension at;

> http://standard.open-contracting.org/profiles/ppp/latest/en/extension.json

This url appears in the following locations in the profiles:

> [technical overview documentation](http://standard.open-contracting.org/profiles/ppp/latest/en/technical/#the-ocds-for-ppps-schema) (in a code formatted block)
> [sample data](http://standard.open-contracting.org/profiles/ppp/latest/en/_static/full.json) (in the extensions key)

Currently these all point to the `/latest/en` version of the consolidated extension, which is fine because we only have one version and the consolidated extension is untranslated.

Related to #157 and #159, once we have multiple versions and languages of the extension, we will need to replace the version and language segments of these urls with placeholders so that they point to the correct place depending on the version and language of the docs the user is viewing.

**Comment by jpmckinney** [comment]
~~Blocked by #159~~

**Comment by jpmckinney** [comment]
Noting that we may need to change `conf.py` to look more like the standard's, i.e. take advantage of the `current_lang` symlink.

**Comment by jpmckinney** [comment]
Per #172, we would no longer have a language as part of the consolidated extension's canonical URL (http://standard.open-contracting.org/profiles/ppp/schema/1__0__0__beta/extension.json).

In the standard, we replace `{{version}}` with e.g. `1.1`, which is used for documentation URLs. We don't replace it with e.g. `1__1__3`, which is used for schema URLs http://standard.open-contracting.org/schema/1__1__3/release-schema.json

As an aside, can anyone remind me where we refer to URLs like http://standard.open-contracting.org/schema/1__1__3/release-schema.json in the documentation?

Anyhow, I don't think we have an existing mechanism for replacing a placeholder with underscored schema versions. For now, I think it's fine to have to manually replace those few instances in which we refer to the profile's version in the documentation. We can add a step to the handbook to remind us.

If all that sounds fine, would it be okay to close this issue?

**Comment by duncandewhurst** [comment]
Yes, I think that all sounds fine. I opened an issue on the handbook to add the reminder once #172 is done.

> As an aside, can anyone remind me where we refer to URLs like http://standard.open-contracting.org/schema/1__1__3/release-schema.json in the documentation?

That url is used in the `id` property of the schema itself:

```json
  "id": "http://standard.open-contracting.org/schema/1__1__3/release-schema.json"
```

But not anywhere else in the docs as far as I'm aware (e.g. the link to download the schema on [this page](http://standard.open-contracting.org/latest/en/schema/release/) points to: http://standard.open-contracting.org/latest/en/release-schema.json)

**Comment by jpmckinney** [comment]
Thanks! I created https://github.com/open-contracting/standard/issues/742 for the aside.
