### ISSUE TITLE
Approvals

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#18]
A PPP process may include many approval processes such as:
- Sign off by the Ministry of Finance
- Checks by the competition authority of bidder eligibility
- Confirmation of process by an auditor or social witness

The PPP Disclosure Framework asks for information on "Dates of various approvals".

Dates of approvals could be modelled with milestones, but this does not capture details of the party making the approval. 

In Mexico we considered whether approvals should be attached to documents - to indicate, for example, who a document was signed by. However, we discussed the fact that signatures on a document does not necessarily imply approval. 

Further work is needed on the concept of approvals, and how they should be modelled in OCDS.

**Comment by duncandewhurst** [comment]
The current proposal is to model these as milestones, see updates to related codelists in #37
