### ISSUE TITLE
Users of Data

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#19]
Here is a summary of the different users of PPP data as defined by the disclosure framework. I listed the users and then what they need the data for. (I've only added a few minor bullets)

I thought to create this in order to:
- help plan for the visualization.
- help with creating user profiles to inform our user experience design.
- make sure the disclosure we do meets the needs of data users.
- have a handy list to refer to.

Please add other user profiles and what they need the data for.
## Potential users of PPP Data

**1. Private companies**
- bidders (Major group)
  - interested in procurement milestones, such as publication of the RFPs
-  parties interested in developing unsolicited proposals
  -  follow up on the soundness of the process and criteria, 
  -  gain a better idea of the projects already underway and potential projects likely to fit within the government’s development plan.
- private sector
  - value-for-money reports
  -  risk allocation issues
  -  understanding of why the winning bidder was chosen and accordingly formulate their own proposals
  -   understand the progress of potential projects coming to market
  -  understand when extended approval processes can impact directly the private
    sector’s costs of bidding.

**2. Trade media** 
- updates on new expressions of interest, RFQs, and RFPs
-  news about project closings is reported
-  regular quarterly and annual reports on project transactions by milestone
-  regular  quarterly and annual reports on the total value and number of closed projects by sector, and region.

**3. Mainstream media** 
- possible corruption or red flags  
-  aspects of the projects related to service quality, social issues, fiscal issues, private investment, financial issues, land, environment, and resettlement etc

**4. Members of the public** 
- The general inference is that a few individuals may be nterested in PPP contracts and data, most likely (local) government representatives and representatives of civil society organizations.

**5. Users of services** 
- interested in the standards of service as well as actual performance.
- service users are understood to be included among the category “general public;” however, users of services are more focused users of project information as it affects them directly.

**6. Government departments** 
- Local government officials working on new but similar projects at the provincial and local levels depend on information and documents disclosed by national PPP units or by other contracting authorities while developing and procuring their own PPP projects.
- government departments, especially those that exercise oversigh rely on the information disclosed for their own reporting and monitoring purposes

**7. Investors** 
- information to assess the viability of projects
  - information to recommend or make decisions on investments

**8. Researchers** 
- information for reports and studies
- raw data for analysis and manipulation

**9. Practitioners and advisors.** 
- Consult the disclosed contracts when they work on new projects that have similarities. This practice seems to have assisted in standardizing contracts and, in particular, risk allocation.
- Find best practices in drafting and structuring projects.

**Comment by dc-coder** [comment]
I think it is tempting to start adding non-human actors to "users of data" - like "Procurement systems", "budget systems" - "corporate registries" etc... 

This can help us in thinking about modelling, because each type of system needs specific pieces of data.

Like the budget systems, usually need to know the risk allocation.
Procurement systems need to know what is being procured and how much
Corporate Registry needs to know the structure of an SPV that was formed for this project.
Financial Systems need to know the Financial model
Audit systems need to know things above a certain threshold or receive flags.

and so on...

In the age of "Internet of things" , can we have "internet of systems" as well? the data standard is meant to help create this network of system and make it inter-operable .... and not just serve the ultimate users of data, but also the intermediaries... so those are just some thoughts to expand our "users of data" to non humans.

**Comment by jpmckinney** [comment]
@dc-coder What is the intention of this issue?

**Comment by jpmckinney** [comment]
Not clear of intention of issue, so closing.
