### ISSUE TITLE
Capturing minutes of meeting

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#20]
The PPP framework mentions multiple times that the minutes of meeting - for example with bidders - need to be captured.
I was wondering if the "documents" can actually be multimedia. (video recording from VC etc)

This might add more transparency but I am not sure if this opens a whole pandora box of terminology and having to provide guidelines on the documents or multimedia file formats/extensions.

**Comment by timgdavies** [comment]
The [documents](http://standard.open-contracting.org/latest/en/schema/reference/#document) building block of OCDS uses a ```format``` codelist which uses full [IANA Mimetypes list](http://www.iana.org/assignments/media-types/media-types.xhtml) which does allow documents to be multi-media items.

We would perhaps want to add entries to the ```documentType``` codelist to allow consuming applications to better understand and content is video etc. 

We could also in our visualisation library model how documents of different mime-types can be best displayed to users (it might make sense from display perspective to draw distinction between the different doc types).
