### ISSUE TITLE
Financing type codelist

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#21]
Just spoted https://openfigi.com/

We should explore if any linkages here with the financial instruments funding PPPs.

**Comment by dc-coder** [comment]
Do you wanna try to identify a codelist of "financial instruments"? I can help compile it by asking around. or are you pondering if it will be interesting in the first place?

**Comment by timgdavies** [comment]
I'm not sure if it will be useful or not: but if you can ask around to see if there are commonly used lists that would be great.

**Comment by dc-coder** [comment]
Here is some feedback from Shyamala:

> Both debt and equity instruments are used to finance PPPs, senior debt, mezzanine debt, sub-equity, equity. 
Debt can also be through bond issues. The bonds themselves can be of different kinds. These are of different types and ever changing and also have different names based on who we are dealing with. 

> This level of harmonization would be very difficult. We may end up complicating stuff beyond a reasonable level if we tried to harmonize. 

> Also new financial instruments keep coming up within different categories. I would suggest doing just equity, and then senior and junior debt, maybe they can also include bond financing as a category under the debt.

Hope this is helpful a bit :)

**Comment by timgdavies** [comment]
There is a [draft financeType codelist here](https://docs.google.com/spreadsheets/d/1qipg79qQReqWgKzn7mRhsriA6V8HCtKkg9GaZO32EUI/edit#gid=1594285097) based on the notes above.
