### ISSUE TITLE
Should sector be a simple codelist, or offer a range of classification schemes?

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#22]
Section I.1 of the PPP disclosure framework asks for a description of the sector a project is taking place in.

No codelist for sectors is specified. 

The World Bank [PPP Knowledge Lab](https://pppknowledgelab.org) uses the following top-level list of sectors:
- Agribusiness
- Education
- Health
- ICT
- Municipal
- Power
- Tourism
- Transport
- Water & Sanitation

The [PPP in Infrastructure Resource Center](http://ppp.worldbank.org/public-private-partnership/) uses the following breakdown:
- Clean Technology
- Energy and Power
- Subnational and Municipal
- Municipal Solid Waste
- Telecom and ICT
- Transportation
- Water and Sanitation

The [Private Participation in Infrastructure Database](https://ppi.worldbank.org/) uses:
- Airports
- Electricity
- ICT
- Natural Gas
- Ports
- Railways
- Roads
- Water and sewerage

The draft extension I'm working on proposes introducing two fields:
- `sector` - with values drawn from a codelist based on the PPP Knowledge Lab list
- `subSector` - allowing for free-text specification of more detailed sectors.

**Comment by dc-coder** [comment]
I think it is more useful to have the sector as codelists, because as we merge databases or as we want to compare local and national data for example, a code list makes data more usable.

This is the general World Bank Sector list.
http://www.projects.worldbank.org/sector

I can look  at other international dev. agency and compare.

This is how a bank API defines sectors - my takeaway from looking at this xml, is to define sector code (used for internal data linkages) and sector name which is up for translations etc. 

```<ns1:sector>
<sector_code>HG</sector_code>
<major_sector_code>HX</major_sector_code>
<sector_short_name>Health</sector_short_name>
<sector_long_name>Health</sector_long_name>
<effective_date>2016-07-01</effective_date>
<expiration_date>2199-12-31</expiration_date>
<sector_board_code>HE</sector_board_code>
<major_sector_short_name>(H)Hlth,Nutn&Popultn</major_sector_short_name>
<major_sector_long_name>(Historic)Health, Nutrition & Population</major_sector_long_name>
<major_sector_effective_date>1993-07-15</major_sector_effective_date>
<major_sector_expiration_date>2001-12-06</major_sector_expiration_date>
</ns1:sector>

**Comment by timgdavies** [comment]
Thanks for pointing to this.

If you can look at what others use that would be great. I'm curious as to whether we could just fix on a codelist (E.g. WB Sector Codelist) here, or whether we would need to have the option for people to specify which codelist they are using etc.

**Comment by dc-coder** [comment]
First, here is list of Worldbank, so whoever is reading this doesn't have to follow external links.

World Bank
- Agriculture, fishing, and forestry
- Public Administration, Law, and Justice
- Information and communications
- Education
- Finance
- Health and other social services
- Energy and mining
- Transportation
- Water, sanitation and flood protection
- Industry and trade

I can think of few other sectors where World Bank and others don't work, like defense or doesn't consider it as "sector" like housing.

From India PPP website, I exported data and got following unique values
- Roads
- Ports
- Housing
- Sports
- Railways
- Tourism
- Civil Aviation

**Kenya**

- Transport 
    - Roads
   -  Airport
   -  Port
    - Railways
- Energy
- Education
- Health
- Water
- Housing
- Agriculture

**Comment by dc-coder** [comment]
Seeing this, i think now i am of the opinion of the letting people choose the codelist... but this is just me, hope others can chip in.

**Comment by timgdavies** [comment]
See https://github.com/open-contracting/standard/issues/399 where COFOG has been suggested as a good basic codelist - and which I think would cross-walk to most of the classifications above.
