### ISSUE TITLE
Disclosure timing

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#24]
One of the recurring themes in PPP Disclosure we found is that some PPP Unit or governments are willing to disclose information but only after another milestone has passed. 

Those milestones could be after a certain study has been completed, an audit, after a process has started - but also sometimes it is after the contract has been signed.

Should the data model capture the timing of disclosure of specific fields or documents? I know that there is a transparency dimension to this that goes beyond data... but some indicators can be built around this and those indicators are useful for the public.

PPP projects are also slow and long, so inserting time as a meta data for fields might be interesting to track progress of disclosure vs progress of project or it is just something to think about.

**Comment by timgdavies** [comment]
This is built into the OCDS releases and records model by default - such that each release should indicate a publication date, and that would tell us when information was first made available. 

So - it should be possible to compare the date information becomes available with the dates of the documents, or contract signature etc. themselves...

**Comment by dc-coder** [comment]
i was thinking more of linking it to milestones... like disclosure is happening "after financial close", "after signature of contract" , "after study xyz"

now that i am thinking of it, i think this can be done just as a visualization tool of the disclosure itself.

Wanna close the ticket?
