### ISSUE TITLE
Should we introduce a new milestone type for commercial/financial close?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#25]
The disclosure framework states that the dates of commercial and financial close should be disclosed. We propose to use milestones to model this information, however none of the milestone types proposed in the [milestones upgrade issue](https://github.com/open-contracting/standard/issues/373) seem appropriate for these dates.

Should we introduce an additional milestone type for these dates and what should it be called?

Some options and considerations:

**negotiation** - financial and commercial close may not strictly be considered negotiations in some procurement regimes (see [here](http://www.eib.org/epec/g2g/iii-procurement/32/321/index.htm))

**contract** - may be ambiguous with other proposed codes

**Comment by dc-coder** [comment]
Some other dates/milestones that may not fit the[ milestone upgrade issue ](https://github.com/open-contracting/standard/issues/373) you linked to:

- Commencement of construction or development
- Completion of construction or development
- Commissioning

And maybe "Contract expiry" can go on that list.

Some other broad dates or milestones are:
- Project proposal received
- Project proposal screened
- Project proposal enters national priority list of projects

This is not to go off-topic... but maybe to say that for milestones in PPP projects, they are very divergent from regular contracting, maybe a different naming for this can be created and added only to PPP extension?

**Comment by duncandewhurst** [comment]
@dc-coder thanks for the feedback, some thoughts in-line below:

> Some other dates/milestones that may not fit the milestone upgrade issue you linked to:
>* Commencement of construction or development
>* Completion of construction or development
>* Commissioning

My initial thought was that these could all map to the proposed ```delivery``` milestone type code, however it's true they don't exactly fit the currently proposed description for that code.

> And maybe "Contract expiry" can go on that list.

We have a ```contractPeriod/endDate``` field in OCDS so would initially propose using that field to capture contract expiry.

Good point that we should consider using a different list of milestone types for the PPP case, though I think we would still want to keep this a short list of **types** and use ```milestone/title``` and ```milestone/description``` to provide details on specific milestones.

**Comment by dc-coder** [comment]
thanks for clarification ... if tweaking a description solves it, then better not add additional blocks :)
Less new stuff makes sure we can re-use previous visualizations at least :) 

Here is a case scenario to consider. for different projects:
People might use different ways to express the start and the end of work. They can use "Building work started, commencement of construction, start of development etc...

In this case, can we still do common analytics or statistics on projects starting/ending in a country? (without having to use natural language processing ;p).

Since the milestone type is a codelist, then another nested codelist sounds weird.

Here is an example.

```javascript 
    {
                        "id":"0003",
                        "type":"delivery",
                        "title":"Building work started",
                        "description":"Building work should start by this date.",
                        "dueDate":"2010-10-01T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      }

```
```javascript  
{
                        "id":"0004",
                        "type":"delivery",
                        "title":"Commencement of construction",
                        "description":"Building work should be complete by this date.",
                        "dueDate":"2011-06-01T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      },
```

```javascript  
{
                        "id":"0005",
                        "type":"delivery",
                        "title":"Start of development",
                        "description":"Building work should be complete by this date.",
                        "dueDate":"2011-06-01T00:00:00Z",
                        "status":"planned",
                        "dateModified":"2010-05-10T09:30:00Z"
                      },```

**Comment by duncandewhurst** [comment]
@dc-coder this is a really good point

I think it would be better to introduce a secondary codelist with detailed ppp specific codes, perhaps ```milestone/tag```, and keep ```milestone/type``` high level, for consistency with core OCDS.

**Comment by duncandewhurst** [comment]
Continued in #37
