### ISSUE TITLE
Organization role codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#26]
The [organizations approach](https://github.com/open-contracting/standard/issues/368) proposed for the OCDS upgrade includes the addition of an ```organization/role``` field and associated codelist.

What values should this codelist contain for the PPP scenario?

The following organization types appear in the disclosure framework:

* sponsoringAgency
* publicAuthority
* privateParty
* leadFinancier
* financier
* bidder
* shareholder
* consortiaMember

We should also bear in mind that in the case of Red Compartida a separate entity was created during the procurement process which will be responsible for contract management of the successful SPV.

**Comment by duncandewhurst** [comment]
**preferredBidder** also appears in the disclosure framework (II.9)

We need to understand whether this should be added to the codelist, i.e. is the following a potential publication pattern:

1. ```release/tag``` = [tenderUpdate], ```organization/role``` = [bidder]
1. ```release/tag``` = [award], ```organization/role``` = [bidder, preferredBidder]
1. ```release/tag``` = [contract], ```organization/role``` = [bidder, preferredBidder, privateParty]

**Comment by dc-coder** [comment]
Let me know if you want me to run this codelist by some procurement/PPP specialist. I feel there might be more items in that codelist.
Are you at the time in point where you want to generate a full code list? or just thinking about specific items in a codelist and how to format them?

**Comment by duncandewhurst** [comment]
@dc-coder thanks, we'll certainly want to do that, but right now we're still working through modelling the framework so may have some more to add here before we're ready to invite a specialist to review the list.

**Comment by dc-coder** [comment]
cool - let me know once you are at that stage... the place i am in is swarming with economists and procurement people ;p

**Comment by duncandewhurst** [comment]
The proposed codes, titles and descriptions for **organizationRole** codelist are documented in this [Google Sheet](https://docs.google.com/spreadsheets/d/1qipg79qQReqWgKzn7mRhsriA6V8HCtKkg9GaZO32EUI/edit#gid=1160323424) for consultation.

We are inviting feedback on

- Whether the proposed codes are sufficient to describe the types of organizations involved in the PPP contracting process.
- Whether the proposed codes are sufficient to perform the types of analysis needed about organizations involved in the PPP contracting process.

Feedback can be provided either as comments in the Google Sheet or as responses to this issue.
