### ISSUE TITLE
Document Type codelist

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#27]
The disclosure framework includes several types of document.

The table below maps the documents included in the disclosure framework to the existing [document type codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#document-type) and proposes new codes where neccessary:

Framework element | Existing document type | Proposed document type
---------------------|-------------------------|----------------------
I.4: Project need: benefits provided, economic and social (including specific information on the public interest aspect) | needsAssessment | n/a
I.5: Technical description of the physical infrastructure | technicalSpecifications | n/a
I.6: High-level description of the services | n/a | serviceDescription
I.7: Estimated demand to be served annually | n/a | estimatedDemand
I.9: Reason for selection of PPP mode and type in brief | n/a | pppModeRationale
I.17: Links to all contract documents | contractSigned, contractArrangements, contractSchedule, contractAnnexe, contractGuarantees | n/a
II.1. Timeline, final feasibility study, independent auditor's report* | feasibilityStudy, environmentalImpact, finalAudit | n/a
II.2. RFQ documents | biddingDocuments** | n/a
II.4. RFP documents | biddingDocuments | n/a
II.5. Evaluation criteria: brief description with weightage | evaluationCriteria | n/a
II.6. Brief information on constitution of the evaluation committees | n/a | evaluationCommittee
II.7. Negotiation parameters: brief descrtiptoin of the parameters for negotiation with preferred proponent | n/a | negotiationParameters
II.8. Minutes of pre-bid meetings | n/a | preBidMeetingMinutes

*The disclosure framework provides further detail on this point: _final feasibility study, including land acquisition, social, environmental, and rehabilitation related information, reports of independent procurement  auditors (if any)_

**The [draft implementation guidance](https://github.com/open-contracting/standard/blob/ppp-extension/standard/docs/en/implementation/ppp_framework.md) recommends that the RFQ and RFP stages of a PPP procurement are modelled as two linked contracting processes in OCDS. In which case the RFQ documents would effectively be the bidding documents for the first contracting process. Using the biddingDocuments code accommodates the different ways the first contracting process might be named (e.g. RFQ, pre-qualification, shortlisting).

This table is complete for sections I - III of the disclosure framework and this issue will be updated with mappings and proposed codes for subsequent sections of the disclosure framework.

We're inviting feedback on both the existing mapping and proposed codes.

**Comment by dc-coder** [comment]
For the following items: 
- Estimated demand to be served annually
- Evaluation criteria: brief description with weightage

Do you think it will be better and more "data friendly" if they are not created as "documents" but as Data Cubes or in a matrix format (in the same way that risks and performance indicators are modeled?)

If they are documents, it will be very hard to use them as data. For example,

-  "The estimated demand to be served annually" can be very important to compare to key performance indicator and to visualize it over time, do the predicted vs actual and see if the private sector is delivering.

- The evaluation criteria can be very important in generating red flags and comparing different bidders and offers.

So, my questions, are those two items better off outside this list?

**Comment by dc-coder** [comment]
Links to all contract documents code-list, should it also include negotiationsCriteria?)

**Comment by duncandewhurst** [comment]
@dc-coder you can find the working draft guidance for these areas [here](https://github.com/open-contracting/standard/blob/ppp-extension/standard/docs/en/implementation/ppp_framework.md) this is still very much a work in progress but should provide some additional context to the issues we're raising. 

> For the following items:
> * Estimated demand to be served annually
> * Evaluation criteria: brief description with weightage

> Do you think it will be better and more "data friendly" if they are not created as "documents" but as Data Cubes or in a matrix format (in the same way that risks and performance indicators are modeled?)

In general we're trying to prefer reusing existing OCDS building blocks and fields over adding new fields, unless there is a good use case for disclosing the information as structured data, which it sounds like there is for the points you've raised.

**Estimated demand to be served annually**
Would modelling this as a simple ```quantity```, ```unit``` pair be sufficient? For example for a toll bridge (reusing the existing [unit building block](http://standard.open-contracting.org/latest/en/schema/reference/#unit):

```json
"annualDemand": {
    "quantity": 29200000,
    "unit": {
        "name": "trips"
    }
}
```

Or are there cases where annual demand would need to be more complex than a single figure?

**Evaluation criteria: brief description with weightage**
The draft guidance has an and/or approach to evaluation criteria, allowing this to be specified as structured data using the approach discussed [here](https://github.com/open-contracting/standard/issues/223) with draft schema [here](https://github.com/duncandewhurst/ocds-requirements-extension), or in a document.

I think in both cases we would still want to include document types for this information as some publishers may have prepared documents, based on the disclosure framework or otherwise, so we should give them a space to disclose these, hopefully in addition to the structured data.

**Comment by dc-coder** [comment]
You are right, it is better to have both options for disclosure of these things - as docs and as structured data... the implementation team can combine or choose one or the other based on the context.

As for

**Demand**
Yes, the proposed model for demand looks sufficient.

```javascript
"annualDemand": [{
    "period" : {
        "startDate" : "",
        "endDate" : ""
    },
    "quantity": 29200000,
    "unit": {
        "name": "trips"
    }
}]```

I would put demand, not annual demand - because it may not be annual really (might be quarterly or over 2-3 years). The start and end date kinda indicate that.

Is there a flag that shows if this is estimated or actual? or is it not needed/not applicable?

**Evaluation Criteria**
I'll check the schema - but if you already have an extension for that, i bet that is enough.

**Comment by duncandewhurst** [comment]
Framework element **I.8: Project additionality** may also be provided as a document

**Comment by timgdavies** [comment]
I've worked on the metrics extension for use to provide forecasts of annual demand. 

This is now in https://github.com/open-contracting/ocds_metrics_extension and will be in the next draft of the docs.

**Comment by dc-coder** [comment]
Looks good :D

I am wondering if the metrics can be used to measure things that should not happen as an indicator of a good performance. for example, in communication or electricity, the maximum number of internet or electricity outages should be a max of 5 hours. 
Is there a flag that needs to be added for this in the metrics extension?

Also, could there be a need for the metrics to include geolocation? for things like roads etc. or for example, in big projects, different areas might have different metrics...should there be multiple entries that are just differentiated by description or could there be a connection somehow to the location extension?

Let me know if you rather have this discussion on the metrics extension.

**Comment by timgdavies** [comment]
Framework element VI.1 requires:

* contractGuarantees - which we already have

and

* a code for 'fiscal commitments and contingent liabilities disclosure reports' which we need to come up with.

**Comment by timgdavies** [comment]
I've put together a full spreadsheet of [documentType](https://docs.google.com/spreadsheets/d/1qipg79qQReqWgKzn7mRhsriA6V8HCtKkg9GaZO32EUI/edit#gid=1103312832) codes found in the framework [here](https://docs.google.com/spreadsheets/d/1qipg79qQReqWgKzn7mRhsriA6V8HCtKkg9GaZO32EUI/edit#gid=1103312832). 

I've tried to indicate which section I think these documents would be used in, and to highlight when we would be expecting a summary text, and when we might just be expecting a link out to a separate document.
