### ISSUE TITLE
Where should financier information be located?

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#28]
The [disclosure framework](http://pubdocs.worldbank.org/en/773541448296707678/Disclosure-in-PPPs-Framework.pdf) states that parties to the contract should be disclosed, including:

* I.18: Public authority: name of authority, name of representative, address, telephone, fax, e-mail
* I.19: Private party: name of company or consortium, name of representative, address, telephone, fax, e-mail
* I.20: Financiers: name of Lead FI, other FIs, name of representative of lead FI, address, telephone, fax, e-mail

In OCDS the parties to the contract are in the following locations (renaming these fields for the ppp scenario is discussed in #4):

* ```release/buyer```
* ```award/suppliers``` (i.e. not at contract level)

Adding an ```award/financiers``` field to capture information on financiers would be consistent with the location of ```award/suppliers``` however the [European Investment Bank's PPP guide](http://www.eib.org/epec/g2g/iii-procurement/32/322/index.htm) states that:

> In difficult financial market conditions (e.g. reduced liquidity), fully committed financing packages may be difficult to obtain at the time of bidding. This may mean that the financing agreements will not be concluded immediately once the PPP contract is signed.

Since information on financiers may not be available at the time of award, would ```contract/financiers``` be a better location that ```award/financiers```?

**Comment by dc-coder** [comment]
I got the following feedback on this:

There's never a financing agreement at the time of bidding or award. It **always** comes after signing of the agreement. That is what is called financial close. Award is not the right place.

**Comment by timgdavies** [comment]
We are including the finance table within contract.
