### ISSUE TITLE
Making documents more user friendly

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#29]
Hey!

One of the challenges of disclosing documents is that they are gigantic and detailed and finding bits of information is hard.

I was wondering if you decided to model any "bookmarks" inside the documents... for example, if i want a section "risks" - it is bookmarked at "page 41", if i want something on  performance, it is on "page 10, 61 and 89" - if i want "approvals and committee members it is on page "10"

Then in any front-end the document viewer can have those highlights or bookmarks on the side.

This is obviously an advanced level disclosure... but it can also serve as disclosure for the lazy... upload documents and provide the highlights... i was just wondering if any work on this was considered... it might be something to nest under documents.

**Comment by duncandewhurst** [comment]
This is exactly something that is being considered since it came up in our initial research.

One challenge we need to be aware of is that there can often be a difference between the page number of the PDF (for example) and the page number of the document, so we need to make sure that the documentation contains appropriate guidance for both publishers and users in this respect.

It would be interesting if tooling for publishers could actually insert the bookmarks into a PDF document, so that the document + bookmarks could be self contained for anyone downloading to read offline for example.

**Comment by dc-coder** [comment]
> One challenge we need to be aware of is that there can often be a difference between the page number of the PDF (for example) and the page number of the document, 

Totally agree... i found this quiet annoying a few times... 

In PPP case, some pages from contracts might be omitted or redacted... so this is likely to come up in this type of documents.

I think the data model needs to be true to the real data/real life.... not scanned documents (they might change over time or the software used to read them) 

So my suggestion would be to maybe model the data as physical page number and scanned page number? (both options?)

if those are the same, in the UI we can add a checkbox that says "PDF and Scanned document have the same numbering"... (same UI when billing and shipping information are the same)

If there is a difference, the checkbox can be un-ticked and PDF page numbering can be edited... 

This is all to say... that my suggestion to have both doesn't have to be that cumbersome in UI terms and it covers the exceptions when we have redacted pages.

I would also use the differences to kinda build a redflag that shows if a lot of published documents have tons of missing information.

**Comment by timgdavies** [comment]
We're looking at at an approach that combines two approaches:

* (1) Using [schema.org's pageStart](https://schema.org/pageStart) and [pageEnd](https://schema.org/pageEnd) properties to extend the document block with information that points to the **printed page number** where the information can be found 

* (2) Recommending that publishers use the [#page=n](https://helpx.adobe.com/acrobat/kb/link-html-pdf-page-acrobat.html) feature at the end of their URLs to point to specific pages (as this appears to be widely supported by browsers).

**Comment by timgdavies** [comment]
The [documentation extension](https://github.com/open-contracting/ocds_documentation_extension) covers the points discussed here.
