### ISSUE TITLE
Project additionality

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#32]
The framework asks for ‘Project additionality’, but does not include any definition of additionality. 

Based on the literature, and additionality sections in existing PPP documentation, we understand this to be a narrative description of the benefits the project brings. 

It would be useful to provide a more detailed definition of whether this should be:

* The additionality of the project itself, whatever method of finance is used;

Or

* The additionality that results from the selection of a PPP modality;

We have assumed that, given the diversity of project goals, it is not possible to capture structured data on additionality, nor that additionality should be captured as a structured data monetary value.

**Comment by timgdavies** [comment]
Related to #27

**Comment by dc-coder** [comment]
Looking at the IFC disclosure website on[ this link](http://www.ifc.org/wps/wcm/connect/Topics_Ext_Content/IFC_External_Corporate_site/Sustainability+and+Disclosure/Disclosure+Portal): 

If you check the "Development Result" tab, there is a section there for project additionality... i am sharing  some screenshots from different projects.

![additionality1](https://cloud.githubusercontent.com/assets/521705/20283079/8f592fb6-aa85-11e6-9f41-38246c9e1349.PNG)

![additionality2](https://cloud.githubusercontent.com/assets/521705/20283085/9469dba4-aa85-11e6-9492-d6ccff01424d.PNG)

Based on other research i've done,  I also tend to say that it is unstructured data. I will be asking PPP specialists for their feedback and get back to you.

As for the second part of the issue, is it additionality of project itself or of PPP modality... i am also trying to figure it out :)
