### ISSUE TITLE
Modelling qualification phase

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#36]
We have been reviewing the current proposal which asks for the qualification phase to be modelled using a ```relatedProcess``` with it's own tender and award section.

This introduces complexity as it means that **the PPP framework disclosures are split across two contracting processes**.

It is then not clear which process key documentation should be attached to. 

We are considering remodelling this so that:

* A ```qualification``` section is added to the release (alongside ```tender``` etc.) 
* ```qualification```, ```qualificationUpdate``` and ```shortlist``` release types are added to the releaseType codelist.
* An optional ```qualificationBids``` section is included also.

Information on qualified bidders would then be captured in the ```parties``` array with tags to indicate the organisation status. 

The process would then run something like this:

| n | Release | Sections completed | Information provided |
|---|---------|---------------------|----------------------|
| 1 | planning | planning | Background documents etc. |
| 2 | planning | planning, qualification, tender | Details of the proposed procurement methods |
| 3 | qualification | qualification | Invitation to qualify | 
| 4 | qualificationUpdate | qualification | Any documents from enquiries period during qualification |
| 5 | shortlist | qualification, parties, qualificationBids (optional) | A list of shortlisted bidders added to parties |
| 6 | tender | tender | Tender information |
| 7 | award | award | Award information |
| 8 | contract | contract | Contract information |
| 9 | implementation | contract/implementation | Implementation information |

**Comment by timgdavies** [comment]
If we go this route, we need to check our terminology around terms such as 'qualification' and 'shortlist' to make sure we don't exclude particular methods.

We also need to identify how this approach would apply to framework contracts in main OCDS. Would this become an optional way of doing frameworks also?

**Comment by duncandewhurst** [comment]
There is a draft extension [here](https://github.com/open-contracting/ocds_qualification_extension) which adds a qualification section between planning and tender.

@timgdavies currently the extension re-uses the existing tender object, however I think we'll need to create a qualification object to:

* Update field descriptions within the tender object so they make sense in the context of a pre-qualification
* Remove fields which aren't applicable to a pre-qualification, e.g. value, items etc.

I'm not sure this approach would work for frameworks as there would still only be a single qualification and tender, so you wouldn't be able to model the one-to-many relationship between the single contracting process to set up a framework agreement and many call-offs which result from it.

I've added a note to the [frameworks issue](https://github.com/open-contracting/standard/issues/310) in the main standard repository to follow this up though.

**Comment by duncandewhurst** [comment]
The [draft qualification extension](https://github.com/open-contracting/ocds_qualification_extension) has been updated.

This update introduces a new ```preQualification``` object, based on the existing ```tender``` object with updated field titles and descriptions. The following fields from the ```tender``` object have been removed from the ```preQualification``` object:

* preQualification/items
* preQualification/minValue
* preQualification/value

The following guidance will be included in the documentation for the extension:

>A ```preQualification``` release may provide information about the future tender in the ```tender``` section of an OCDS release, for example the items to be procured or the value of the tender. During the pre-qualification process ```preQualification.status``` should be set to ```active``` and ```tender.status``` should be set to ```planned```.

The extension also introduces a ```preQualificationStatus``` codelist, using the same codes as the tenderStatus codelist, with updated descriptions:

code | title | description
-----|------|------------
planned | Planned | This pre-qualification has been proposed, but is not yet taking place. 	 
active | Active | A pre-qualification process is currently taking place. 	 
cancelled | Cancelled | The pre-qualification process has been cancelled. 	 
unsuccessful | Unsuccessful | The pre-qualification process is unsucessful. 	 
complete | Complete | The pre-qualification process is complete. 	 

We are seeking feedback on:

Whether the following fields are applicable to a pre-qualification phase, currently these are included in the ```preQualification``` object:

* procurementMethod / procurementMethodDetails / procurementMethodRationale - would this always be open for the qualification stage?
* awardCriteria / awardCriteriaDetails- the current [awardCriteria codelist](http://standard.open-contracting.org/latest/en/schema/codelists/#award-criteria) doesn't make sense in the context of a pre-qualification process.
* hasEnquiries - is there a need for this data about the qualification stage?
* eligibilityCriteria - the pre-qualification stage defines the eligibility for bidders to participate in the tender. Is a pre-qualification always open or could there be restrictions on those able to participate in this stage?

Whether the following fields need to be renamed:

* ```qualification.awardPeriod``` - would ```qualification.selectionPeriod``` be appropriate?
* ```qualification.numberOfTenderers``` and ```qualification.tenderers``` -  would ```qualification.respondents``` be appropriate?
