### ISSUE TITLE
Moving away from buyer<->supplier model

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#4]
(Reflections from reading [PPP Disclosure Framework](http://www.worldbank.org/en/topic/publicprivatepartnerships/brief/a-framework-for-disclosure-in-public-private-partnership-projects))

OCDS currently is based around the idea of a **buyer** organisation and a **supplier**.

In PPPs there may be many more parties involved in a process, and different flows of finance between private and public parties.

https://github.com/open-contracting/standard/issues/264 proposes introducing a more flexible model to identify organisations.

**Comment by duncandewhurst** [comment]
Our [approach to organizations](https://github.com/open-contracting/standard/issues/368) proposed for the OCDS upgrade allows us to be more flexible but still retains the ```buyer``` and ```award/suppliers``` fields, the terminology for which may not be appropriate for the PPP scenario.

The disclosure framework uses the terms *public authority* and *private party* for the parties to the contract. Should we adopt these in place of ```buyer``` and ```supplier```?

The disclosure framework also includes *sponsoring agency/department*, we should investigate whether this would ever be a different entity to the *public authority*
