### ISSUE TITLE
indicatorValue type

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#40]
The description of the ```indicatorValue``` property states this should be a numeric value, however the schema patch defines the type as ```number```, ```string``` or ```null```:

```JSON
"indicatorValue": {
       "title":"Value",
       "description":"A numerical value for this indicator",
       "type":["number","string","null"]
}
```

Should we update the type to be ```number``` or ```null``` or could non-numeric values be provided against any of the indicators?

**Comment by timgdavies** [comment]
My initial reaction is to say we should leave possibility of non-numerical indicators and update the description accordingly.

**Comment by duncandewhurst** [comment]
Thanks Tim - I've updated the description in [this commit](https://github.com/open-contracting/public-private-partnerships/commit/e55e29f799f4cceeda3411fca01e53c8b514af79)
