### ISSUE TITLE
Removing deprecated fields from the PPP schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#43]
Currently the PPP schema includes deprecated fields from the V1.1 upgrade (see example below).

Is there an easy way to remove these since they're not relevant for users implementing the PPP schema?

![image](https://cloud.githubusercontent.com/assets/19265814/25231054/2b7d8842-25ce-11e7-9c02-076d6d105912.png)

**Comment by timgdavies** [comment]
We should set these to null in a schema patch, or have a quick script that strips them out before we push the docs up.
