### ISSUE TITLE
Update links to OCDS Show to work in multi-lingual site

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#53]
We have links at http://ocds-for-ppps.readthedocs.io/en/latest/example/ and http://ocds-for-ppps.readthedocs.io/en/latest/overview/ that were previously opening OCDS Show in a pop-up window - but now we have gone to multi-lingual ReadTheDocs, these links don't work.

We need to update them, either with relative paths to work with versions/languages, or with some replacement tokens?

**Comment by timgdavies** [comment]
@Bjwebb Is the only way to make these relative? Or can we add a token that gets replaced with base path?

**Comment by Bjwebb** [comment]
I think relative links is going to be the easiest way to do this https://github.com/open-contracting/public-private-partnerships/commit/a7993f17ade65a76c9583f5547ec3022ca06b9410
