### ISSUE TITLE
Handling confidential information

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#6]
(Reflections from reading [PPP Disclosure Framework](http://www.worldbank.org/en/topic/publicprivatepartnerships/brief/a-framework-for-disclosure-in-public-private-partnership-projects))

There may be information in a PPP which cannot be disclosed at time T, but could be disclosed at time T+1.

There is other information which will always remain confidential, but where the fact that the information exists should be public knowledge.

How should we accommodate these cases?

**Comment by jpmckinney** [comment]
Closing as one year without input.
