### ISSUE TITLE
Broken link to JSON schema

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#61]
The link to the full PPP schema on the [schema reference page](http://ocds-for-ppps.readthedocs.io/en/latest/reference/schema/) is broken.

We need to fix the build process so that the schema is copied from /schema to /docs/_static

**Comment by Bjwebb** [comment]
I think the build process is fine, it copies the schema to https://ocds-for-ppps.readthedocs.io/en/latest/_static/ppp-release-schema.json . The link on that page wants updating to be relative: `../../_static/ppp-release-schema.json`.

**Comment by timgdavies** [comment]
This is fixed on master.
