### ISSUE TITLE
Fixing null values in PPP extension and community extensions

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#64]
In working on [OCDS #400](https://github.com/open-contracting/standard/issues/400) I found that we had a community extension which was setting properties from OCDS core to null. 

Only **profiles** rather than **extensions** should be allowed to do this (i.e. we don't want a community extension nulling things out from the core schema). So, I moved these ```null```s to remove fields from the extension, into the PPP release-schema.json.

I then realised that ```apply-extensions.py``` was dropping the ```null```s from the merged ppp-extension.json, so I've also updated that. 

I think to get all this deployed will require steps in the following order:

* [x] Merge [changes to the ocds_budget_projects_extension](https://github.com/open-contracting/ocds_budget_projects_extension/pull/1)
* [x] Merge pull request #62 on this repo to update the ppp release-schema.json
* [ ] Merge pull request ~#63~ #121 on this repo
* [ ] ~~Then run apply-extensions.py on the updated master branch, and commit the changes to schema/ppp-extension.json and schema/ppp-release-schema.json back~~

The steps for codelists in #59 could be part of this workflow as well before the last step I think.

**Comment by jpmckinney** [comment]
Closing in favor of #121.
