### ISSUE TITLE
What's the workflow for ensuring base-release-schema.json is in sync?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#73]

**Comment by timgdavies** [comment]
I don't think there is a set one right now - other than a manual process of fetching updated schema.

There does need to be manual checking with anything other than bug-fix releases.

**Comment by jpmckinney** [comment]
Where is the manual process documented? I don't know what script to use in the extensions.

**Comment by jpmckinney** [comment]
Would an update to this extension be scheduled for the 1.1.1 release?

**Comment by duncandewhurst** [comment]
I've updated the base schema and codelists to v1.1.1 in https://github.com/open-contracting/public-private-partnerships/pull/96 and documented the process for updating these in https://github.com/open-contracting/standard-development-handbook/commit/c74d1f2daf69a69c677d267ca7fe05bbc9680a33
