### ISSUE TITLE
Document how dependent extensions are pulled into this repo

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#74]
I realize some typos I had corrected locally would likely be corrected once the dependent extensions are pulled in. Where is that workflow documented?

**Comment by jpmckinney** [comment]
Noting some harder to detect typos here:

* `contractSchedules` should be `contractSchedule`

**Comment by duncandewhurst** [comment]
> I realize some typos I had corrected locally would likely be corrected once the dependent extensions are pulled in. Where is that workflow documented?

@kindly would you be able to look at updating [https://github.com/open-contracting/public-private-partnerships/blob/master/README-Docs.md](https://github.com/open-contracting/public-private-partnerships/blob/master/README-Docs.md) to explain this?

**Comment by duncandewhurst** [comment]
Documented in https://github.com/open-contracting/standard-development-handbook/commit/c74d1f2daf69a69c677d267ca7fe05bbc9680a33
