### ISSUE TITLE
Possible typo in eval_rst

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#75]
In framework.md, there's:

```
.. jsonschema:: _static/ppp-release-schema.json
    :include: planning/project/additionalClassification
    :collapse: 
    :nocrossref:
```

However, `additionalClassification` occurs nowhere. There is only the plural form `additionalClassifications`.

**Comment by timgdavies** [comment]
Hoping @duncandewhurst can look at this - as it might need fixing in source spreadsheet for the mapping also.

**Comment by duncandewhurst** [comment]
Fixed in https://github.com/open-contracting/public-private-partnerships/commit/02e07c613432b71da37002bb5a98e168b8d2326b and in source spreadsheet
