### ISSUE TITLE
Updating theme

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#79]
Following discussion with Georg and James - I've updated the theme branch with the below color scheme.

![image](https://user-images.githubusercontent.com/342624/29040873-9bbc8d76-7ba8-11e7-869d-21a50ab05a35.png)

To finalise theme updates we need to add the [World Bank logo](http://www.worldbank.org/content/dam/wbr/logo/logo-wb-header-en.svg) under 'Developed by' so that this read:

Developed By: 

'World Bank' and 'Open Contracting Partnership' 

using their logos.

The world bank logo should link to http://www.worldbank.org/en/topic/publicprivatepartnerships/brief/ppp-tools

**Comment by Bjwebb** [comment]
Here's the theme with the world bank logo in it http://standard.open-contracting.org/profiles/ppp/theme/en/
