### ISSUE TITLE
Contradictory license info

### ISSUE THREAD

**Issue by Bjwebb** [open-contracting/public-private-partnerships#80]
https://github.com/open-contracting/public-private-partnerships/blob/master/LICENSE.md says CC-BY
https://github.com/open-contracting/public-private-partnerships/blob/master/LICENSE is a copy of the Apache license

**Comment by jpmckinney** [comment]
The Apache license was in the initial commit, so I expect the intention is to have CC-BY, but Apache survived by accident.

**Comment by LindseyAM** [comment]
We had discussed that ppp extension should have the same license as OCDS

**Comment by duncandewhurst** [comment]
Addressed in https://github.com/open-contracting/public-private-partnerships/pull/81
