### ISSUE TITLE
add a tip about viewing json in browser 

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#83]
On this page, there is a link to the json file
http://standard.open-contracting.org/profiles/ppp/theme/en/example/#explore-the-example

I think it would be useful if you add a tip to the text telling people to install a json viewer in their web browser. Features like ability to collapse blocks of data and color coding might make reading the json more user friendly and less intimidating for non-tech (who end up reading the technical documentation because they have to discuss/demonstrate the use of different publication formats)

This might be useful for the general OCDS documentation or just other pages.

**Comment by timgdavies** [comment]
A pull requests to add that text would be really welcome. 

Otherwise we can look at it when next doing an iteration of the docs. 

(Note to self: we'll have to add a Spanish translation for such a tip as well)

**Comment by jpmckinney** [comment]
Seems closed by #84
