### ISSUE TITLE
Typekit: the domain isn't in the list of published domains 

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#87]
While visiting the documentation on http://ocds-for-ppps.readthedocs.io/en/latest/ , I get the following:

![screen shot 2017-08-16 at 7 53 08 am](https://user-images.githubusercontent.com/521705/29347850-369043dc-8258-11e7-9cf9-c2cb9008c350.png)

Typekit: the domain "ocds-for-ppps.readthedocs.io" isn't in the list of published domains for kit "xpw3jps".

this is probably some settings in typekit :) - I hope it is an easy fix

**Comment by jpmckinney** [comment]
I believe the correct URL is http://standard.open-contracting.org/profiles/ppp/latest/en/

We should perhaps create a redirect or take down that other site.

**Comment by jpmckinney** [comment]
Related: https://github.com/open-contracting/standard-development-handbook/issues/8

**Comment by dc-coder** [comment]
maybe you can update the url from the readme as well. Cuz honestly this is where I click.

https://github.com/open-contracting/public-private-partnerships/blob/master/README.md

**Comment by duncandewhurst** [comment]
Closing as the readthedocs url now redirects to the correct URL and the link in the readme has been updated
