### ISSUE TITLE
In PPP documentation about contract award, reference contract

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#90]
I was reviewing an assessment comparing data from a system to the OCDS-PPP extension. The field "Contract agreement and conditions" was marked as missing. I thought maybe the documentation is not very clear if you are only reading the PPP documentation. So here is a suggestion:

In the text on this link
http://standard.open-contracting.org/profiles/ppp/latest/en/framework/?highlight=contract#ii-8-contract-award
![screen shot 2017-08-16 at 9 38 13 am](https://user-images.githubusercontent.com/521705/29350359-f10f730a-8266-11e7-8292-532e3c8202b6.png)

Maybe you should reference the contract building block on this link 
http://standard.open-contracting.org/latest/en/schema/release/#id1
![screen shot 2017-08-16 at 9 39 09 am](https://user-images.githubusercontent.com/521705/29350365-f96bd20a-8266-11e7-9cc4-89258f6e8212.png)

**Comment by duncandewhurst** [comment]
@dc-coder my understanding was that the contract document would come under [I.13 Contract documents](http://standard.open-contracting.org/profiles/ppp/latest/en/framework/?highlight=contract#i-13-contract-documents) in the framework. Perhaps that section was missed in the comparison?

Or there may be a difference of terminology between "Contract agreement and conditions" and "Contract documents"?

**Comment by jpmckinney** [comment]
We can perhaps add a sentence immediately under 'II.8. Contract award' along the lines of:

"If you are looking to describe the contract agreement and conditions, see I.13 Contract documents."

**Comment by jpmckinney** [comment]
It's not clear that this clarification is needed, so closing.
