### ISSUE TITLE
Add link to shareholder extension

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#91]
The text on this link references the shareholder extension
http://standard.open-contracting.org/profiles/ppp/latest/en/extensions/shareholders/

> Shareholder and ownership details
> The shareholder extension can be used to provide details of the owners of parties involved in a contracting process.

Maybe include a link?

**Comment by timgdavies** [comment]
Moved to extensions issue tracker: https://github.com/open-contracting/ocds-extensions/issues/27
