### ISSUE TITLE
typo - contract docuemnts

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#92]
http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#ix-1-1-contract-docuemnts
![screen shot 2017-08-16 at 9 53 11 am](https://user-images.githubusercontent.com/521705/29350836-c93cc47a-8268-11e7-8fd7-afb5d523306e.png)
![screen shot 2017-08-16 at 9 53 18 am](https://user-images.githubusercontent.com/521705/29350835-c93be712-8268-11e7-87fc-420291924676.png)

**Comment by jpmckinney** [comment]
Duplicate #78
