### ISSUE TITLE
Renegotiations approvals 

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#93]
For the different renegotiations, is there a way to model the data on "approval" of those renegotiations ? 
Like who participated in the renegotiations and maybe who approved from the different sides? (especially government)

This might re-use the parties building block and some dates.... but I am not sure I see such thing under http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#ix-renegotiations 

Any guidance on this?

**Comment by duncandewhurst** [comment]
Approval of renegotiations isn't included in the framework so this would be an extension to the PPP profile.

We are using amendments to represent renegotiations in the PPP profile, so this raises a wider question of how to model approval of amendments.

As such I would suggest opening an issue on the main standard [issue tracker](https://github.com/open-contracting/standard/issues) and proposing some modelling for approval of amendments.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/standard/issues/585
