### ISSUE TITLE
documentType codelist - new suggestions

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#94]
The document type is an open code list...  there is "environmentalImpact" as default.

Would you consider adding as a default:
- Land and settlement impact
- Resettlement and compensation plan 

reference: http://standard.open-contracting.org/profiles/ppp/latest/en/reference/codelists/

**Comment by duncandewhurst** [comment]
These won't make it into the documentType codelist for the initial launch, however they can be added in the next iteration of the PPP profile.

In the meantime you can still use the codes as local extensions to the open codelist.

Could you work with colleagues to provide suitable descriptive text for the proposed codes?

**Comment by jpmckinney** [comment]
Merging with https://github.com/open-contracting/standard/issues/643
